version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      # TODO: Publish to AWS npm registry
      - npm run lint
